<a href="https://colab.research.google.com/github/mustafabozkaya/DeepLearningBootcamp2022/blob/master/Exercise/python_ml/why_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5])

In [9]:
print(type(array))

<class 'numpy.ndarray'>


In [10]:
revenues = [2000,5000,3000,6500,7200,3100,2650,1900,3820,5120,4100]

In [11]:
import time

In [8]:
initial_time = time.time()
sum = 0

In [12]:
initial_time

1665037278.9765842

In [13]:
for i in revenues:
  sum += i
print(sum)
termination_time = time.time()
 
print("Execution Time: ",termination_time-initial_time)

44390
Execution Time:  113.67401456832886


In [14]:
array = np.array(revenues)
 
initial_time = time.time()
 
sum = array.sum()
print(sum)
termination_time = time.time()
 
print("Execution Time: ",termination_time-initial_time)

44390
Execution Time:  0.0034182071685791016


In [15]:
x = ['Ben',500,'Jake','Liz',6000]
print(x)

['Ben', 500, 'Jake', 'Liz', 6000]


In [16]:
for i in x:
  print(type(i))

<class 'str'>
<class 'int'>
<class 'str'>
<class 'str'>
<class 'int'>


In [17]:
arrayx = np.array(x)
print(arrayx)

['Ben' '500' 'Jake' 'Liz' '6000']


In [18]:
for i in arrayx:
  print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [19]:
array2  = np.array([[1, 2, 3], [4, 5, 6]])

In [20]:
print(array2)

[[1 2 3]
 [4 5 6]]


In [21]:
array2.ndim

2

In [22]:
array2.shape

(2, 3)

In [23]:
array2.size

6

In [25]:
array2.argmax()

5

In [26]:
array2.argmin()

0

In [27]:
array2.cumsum(axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [28]:
array2.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [33]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
array2.flatten()

array([1, 2, 3, 4, 5, 6])

In [31]:
array2.flatten(order="F")

array([1, 4, 2, 5, 3, 6])

In [32]:
array2.flatten(order="A")

array([1, 2, 3, 4, 5, 6])

In [34]:
array2.flatten(order="K")

array([1, 2, 3, 4, 5, 6])

In [35]:
array2.reshape(-1,6)

array([[1, 2, 3, 4, 5, 6]])

In [37]:
array2.shape

(2, 3)